name: Playwright tests

on:
  pull_request:
    branches: [main]

jobs:
  changes:
    name: Scan for changes
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.scan.outputs.plugins }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: env dump
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Determine changes
        id: scan
        env:
          HEAD: ${{ github.event.pull_request.head.sha }}
          BASE: ${{ github.event.pull_request.base.sha }}
        run: |
          root=$(pwd)
          cd plugins

          changed=()
          for f in */; do
            if git diff --name-only $BASE $HEAD | grep $f -q; then
              if [[ ! -L "$f" && -f "$f/package.json" ]]; then
                cd $f

                if npm run | grep ui-test -q; then
                  changed+=($f)
                fi
                cd $root/plugins
              fi
            fi
          done

          JSON="[$(echo ${changed[@]} | sed 's/ /,/g')]"
          echo "plugins=$(echo $JSON)" >> $GITHUB_OUTPUT
          echo $JSON
          git diff --name-only $BASE $HEAD
