name: Playwright tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: yarn playwright install --with-deps chromium
      - name: Run tests
        run: bash .github/actions/playwright/test-launch.sh
